### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by verpixelt** [AaronAsAChimp/image-lint#9]
I ran into the following error when I've tried to install your package which unfortunately makes it impossible to use =/
`npm ERR! Failed at the nodegit@0.20.3 install script.`

**Comment by AaronAsAChimp** [comment]
Oh Hi!
nodegit has been a thorn for this project. I'm working on a release without it, but will have to be a major version bump. If you would like to try whats in master and let me know if it works for you, that would be a huge help.

**Comment by AaronAsAChimp** [comment]
Ok, I've published a new version (2.0.0) it will no longer automatically download git repositories.

**Comment by verpixelt** [comment]
@AaronAsAChimp Cool thank you. I'll try it :)
